-- DROP TABLE IF EXISTS acts;
-- CREATE TABLE acts(id serial PRIMARY KEY, name VARCHAR(255));
-- INSERT INTO acts(name) VALUES('Bratislava');
-- INSERT INTO acts(name) VALUES('Budapest');
-- INSERT INTO acts(name) VALUES('Prague');